// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtzwJYFwqv1g8_si6LkKL6kAeU_h9sC2E',
    appId: '1:392489965521:web:fba8ee1c40dc5694dbb2f0',
    messagingSenderId: '392489965521',
    projectId: 'app-teste-da4b2',
    authDomain: 'app-teste-da4b2.firebaseapp.com',
    storageBucket: 'app-teste-da4b2.appspot.com',
    measurementId: 'G-L6KGJXV5TM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfQkgu93txDsEUIPdOuhdqddVKJbCizak',
    appId: '1:392489965521:android:6f37945b912660b7dbb2f0',
    messagingSenderId: '392489965521',
    projectId: 'app-teste-da4b2',
    storageBucket: 'app-teste-da4b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk_x8bREAhNg2zeEQtmnE_BiX6yj6fmrc',
    appId: '1:392489965521:ios:b8c0d67999aa22a9dbb2f0',
    messagingSenderId: '392489965521',
    projectId: 'app-teste-da4b2',
    storageBucket: 'app-teste-da4b2.appspot.com',
    iosBundleId: 'com.example.appteste1',
  );
}
